@startuml
'https://plantuml.com/class-diagram

abstract class AbstractFlyingObject
{
    # locationX: float
    # locationY: float
    # speedX: float
    # speedY: float
    # image: BufferedImage
    # width: float
    # height: float
    # isValid: boolean

    + AbstractFlyingObject(float locationX, float locationY, float speedX, float speedY)
    + forward(): void
    + crash(AbstractFlyingObject flyingObject): boolean
    + getLocationX(): float
    + getLocationY(): float
    + setLocation(float locationX, float locationY): void
    + getSpeedY(): float
    + getImage(): BufferedImage
    + getWidth(): float
    + getHeight(): float
    + notValid(): boolean
    + valid(): boolean
    + explode(): void
    + vanish(): void
}

abstract class AbstractAircraft extends AbstractFlyingObject
{
	# maxHp: int
    # hp: int
	# shootStrategyFactory: AbstractShootStrategyFactory
	# shootStrategy: ShootStrategy
	- power: int
    + AbstractAircraft(float locationX, float locationY, float speedX, float speedY, int hp, int power, AbstractShootStrategyFactory strategyFactory, int shootNum)
    + setShootNum(int shootNum): void
    + decreaseHp(int decrease): void
    + getHp(): int
    + getMaxHp(): int
    + shoot(): List<? extends AbstractBullet>
    + getAnimation(): DyingAnimation
}

class HeroAircraft extends AbstractAircraft {
    - {static} INSTANCE: HeroAircraft
    - HeroAircraft(float locationX, float locationY, int hp, int power, int shootNum)
    + getInstance(): HeroAircraft
    + forward(): void
    + increaseHp(int increment): void
    + reset(): void
}

abstract class AbstractEnemy extends AbstractAircraft {
    + AbstractEnemy(float locationX, float locationY, float speedX, float speedY, int hp, int power, int shootNum)
    + prop(): List<AbstractProp>
    + getCredits(): int
}

class MobEnemy extends AbstractEnemy {
    + MobEnemy(float locationX, float locationY, float speedX, float speedY, int hp)
    + getCredits(): int
}

class EliteEnemy extends AbstractEnemy {
    - propFactory: AbstractPropFactory
    + EliteEnemy(float locationX, float locationY, float speedX, float speedY, int hp, int power)
    + prop(): List<AbstractProp>
    + getCredits(): int
}

class BossEnemy extends AbstractEnemy {
    - propFactory: AbstractPropFactory
    + BossEnemy(float locationX, float locationY, float speedX, float speedY, int hp, int power, int shootNum)
    + forward(): void
    + prop(): List<AbstractProp>
    + getCredits(): int
    + explode(): void
}

abstract class AbstractBullet extends AbstractFlyingObject {
    - power: int
    + AbstractBullet(float locationX, float locationY, float speedX, float speedY, int power)
    + forward(): void
	+ getPower(): int
}

class HeroBullet extends AbstractBullet {
    + HeroBullet(float locationX, float locationY, float speedX, float speedY, int power)
}

class EnemyBullet extends AbstractBullet {
    + EnemyBullet(float locationX, float locationY, float speedX, float speedY, int power)
}

abstract class AbstractProp extends AbstractFlyingObject {
    + AbstractProp(float locationX, float locationY, float speedX, float speedY)
    + {abstract} activate(GamePanel game): void
}

class BloodProp extends AbstractProp {
    + BloodProp(float locationX, float locationY, float speedX, float speedY)
    + activate(GamePanel game): void
}

class BombProp extends AbstractProp {
    + BombProp(float locationX, float locationY, float speedX, float speedY)
    + activate(GamePanel game): void
}

class BulletProp extends AbstractProp {
    - usedCount: AtomicInteger
    + BulletProp(float locationX, float locationY, float speedX, float speedY)
    + activate(GamePanel game): void
}

@enduml